name: gpu_locscale
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.7
  - numpy
  - gfortran
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - mpi4py=3.1
  - openmpi=4.1.2
  - pip
  - pip:
      - locscale